/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS12.width_h_
#define _ComicSansMS12.width_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS12.width[];
extern const int ComicSansMS12.width_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS12.width_h_
//---------------------------------------------------------------------------------
