/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS12.height_h_
#define _ComicSansMS12.height_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS12.height[];
extern const int ComicSansMS12.height_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS12.height_h_
//---------------------------------------------------------------------------------
