/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _LucidaConsole10.width_h_
#define _LucidaConsole10.width_h_
//---------------------------------------------------------------------------------
extern const unsigned char LucidaConsole10.width[];
extern const int LucidaConsole10.width_size;
//---------------------------------------------------------------------------------
#endif //_LucidaConsole10.width_h_
//---------------------------------------------------------------------------------
